-- Core social schema for Supabase
-- Tables: profiles, posts, media, tags, post_tags

-- Keep update timestamps current.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  full_name text,
  avatar_url text,
  bio text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  content text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.media (
  id uuid primary key default gen_random_uuid(),
  post_id uuid not null references public.posts(id) on delete cascade,
  type text not null check (type in ('image', 'video', 'audio', 'other')),
  url text not null,
  alt_text text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.post_tags (
  post_id uuid not null references public.posts(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (post_id, tag_id)
);

-- Indexes
create index if not exists idx_posts_profile_id on public.posts(profile_id);
create index if not exists idx_posts_created_at on public.posts(created_at desc);

create index if not exists idx_media_post_id on public.media(post_id);
create index if not exists idx_media_type on public.media(type);

create unique index if not exists idx_tags_name_lower on public.tags(lower(name));

create index if not exists idx_post_tags_tag_id on public.post_tags(tag_id);

-- Update timestamp triggers
create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

create trigger set_posts_updated_at
before update on public.posts
for each row
execute function public.set_updated_at();

create trigger set_media_updated_at
before update on public.media
for each row
execute function public.set_updated_at();

create trigger set_tags_updated_at
before update on public.tags
for each row
execute function public.set_updated_at();
